"""
Dream Decoder - PDF Generator Service
Handles the creation of PDF documents for dream entries
"""
from fpdf import FPDF
from datetime import datetime
import io

class DreamPDF(FPDF):
    def header(self):
        # Logo
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(47, 65, 87) # Midnight Blue
        self.cell(0, 10, 'Dream Decoder', ln=True, align='C')
        self.set_font('helvetica', 'I', 10)
        self.set_text_color(87, 124, 142) # Ocean Mist
        self.cell(0, 10, 'Dream Journal & Psychological Analysis', ln=True, align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by Dream Decoder on {datetime.now().strftime("%Y-%m-%d %H:%M")}', align='C')

def sanitize_text(text):
    """
    Sanitize text to avoid PDF encoding errors (standard Helvetica only supports Latin-1).
    Replaces common non-Latin-1 characters with ASCII equivalents.
    """
    if not text:
        return ""
    if not isinstance(text, str):
        return str(text)
    
    # Common replacements for curly quotes, ellipses, etc.
    replacements = {
        '\u2018': "'", '\u2019': "'",  # Smart quotes
        '\u201c': '"', '\u201d': '"',  # Smart double quotes
        '\u2026': '...',               # Ellipsis
        '\u2013': '-', '\u2014': '--',  # En/Em dashes
    }
    
    for old, new in replacements.items():
        text = text.replace(old, new)
        
    # Final cleanup: encode to latin-1 and ignore anything else
    # This ensures no FPDFUnicodeEncodingError is thrown
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_dream_pdf(dream):
    """
    Generate a PDF for a single dream entry
    :param dream: Dream model instance or dictionary
    :return: BytesIO object containing the PDF data
    """
    pdf = DreamPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Dream Title / Date
    created_at = dream.get('created_at', 'Unknown Date')
    if isinstance(created_at, datetime):
        date_str = created_at.strftime("%B %d, %Y at %I:%M %p")
    else:
        # Assuming ISO format string if not datetime object
        try:
            dt = datetime.fromisoformat(created_at.replace('Z', '+00:00'))
            date_str = dt.strftime("%B %d, %Y at %I:%M %p")
        except:
            date_str = created_at

    pdf.set_font('helvetica', 'B', 14)
    pdf.set_text_color(47, 65, 87)
    pdf.cell(0, 10, f'Dream Entry: {sanitize_text(date_str)}', ln=True)
    pdf.ln(5)

    # Dream Content
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Dream Content:', ln=True)
    pdf.set_font('helvetica', '', 11)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 7, sanitize_text(dream.get('content', 'No content available')))
    pdf.ln(10)

    # Analysis Section
    pdf.set_draw_color(87, 124, 142)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(47, 65, 87)
    pdf.cell(0, 10, 'AI Analysis:', ln=True)
    
    # Emotion
    pdf.set_font('helvetica', 'B', 10)
    pdf.cell(40, 7, 'Primary Emotion:', 0)
    pdf.set_font('helvetica', '', 10)
    pdf.cell(0, 7, sanitize_text(dream.get('primary_emotion', 'Neutral').capitalize()), ln=True)
    
    # Sentiment
    pdf.set_font('helvetica', 'B', 10)
    pdf.cell(40, 7, 'Sentiment:', 0)
    pdf.set_font('helvetica', '', 10)
    pdf.cell(0, 7, sanitize_text(dream.get('sentiment', 'Neutral').capitalize()), ln=True)
    
    # Interpretation Section (New)
    interpretation = dream.get('interpretation', {})
    if interpretation:
        pdf.ln(5)
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_text_color(47, 65, 87)
        pdf.cell(0, 10, 'Psychological Interpretation:', ln=True)
        
        # Numbered Elements
        elements = interpretation.get('numbered_elements', [])
        for el in elements:
            pdf.set_font('helvetica', 'B', 10)
            pdf.set_text_color(87, 124, 142)
            pdf.cell(0, 7, f"{el.get('number', '')}. {sanitize_text(el.get('element', ''))}", ln=True)
            
            pdf.set_font('helvetica', 'B', 9)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(10, 6, '') # Indent
            pdf.cell(0, 6, 'Symbolic Meaning:', ln=True)
            
            pdf.set_font('helvetica', '', 9)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(15, 6, '') # Indent more
            pdf.multi_cell(0, 5, sanitize_text(el.get('symbolic_meaning', '')))
            
            pdf.set_font('helvetica', 'B', 9)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(10, 6, '') # Indent
            pdf.cell(0, 6, 'Subconscious Insight:', ln=True)
            
            pdf.set_font('helvetica', '', 9)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(15, 6, '') # Indent more
            pdf.multi_cell(0, 5, sanitize_text(el.get('subconscious_insight', '')))
            pdf.ln(3)

        # Overall Interpretation
        if interpretation.get('overall_interpretation'):
            pdf.set_font('helvetica', 'B', 10)
            pdf.set_text_color(47, 65, 87)
            pdf.cell(0, 10, 'Overall Interpretation:', ln=True)
            pdf.set_font('helvetica', '', 10)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(0, 6, sanitize_text(interpretation['overall_interpretation']))
            pdf.ln(5)
            
        # Final Insight
        if interpretation.get('final_insight'):
            pdf.set_font('helvetica', 'I', 11)
            pdf.set_text_color(87, 124, 142)
            pdf.multi_cell(0, 7, f"Reflective Insight: {sanitize_text(interpretation['final_insight'])}", align='C')
            pdf.ln(5)
    
    # Return as buffer
    pdf_output = io.BytesIO()
    pdf_bytes = pdf.output()
    pdf_output.write(pdf_bytes)
    pdf_output.seek(0)
    return pdf_output
